---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  A template for EC2 instance creation

Parameters:
  EC2InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: EC2 instance type.

  EC2AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-west-2a
    Description: EC2 instance availability zone.

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03d5c68bab01f3496
      InstanceType: 
        Ref: EC2InstanceType
      AvailabilityZone: !Ref EC2AvailabilityZone

Outputs:
  PublicIp:
    Description: The Instance Piblic IP
    Value: !GetAtt MyEC2Instance.PublicIp
  InstanceID:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
